N=80
N_occ=100

J=-1.0
K=-0.5
f=0.0

Time=20000

PBC = 0 # 0: No Periodic Boundary Conditions
	   # 1: Periodic Boundary Conditions

output = 'final'

Bond_Color_Grid = 0 # 0: No Grid
                    # 1: Grid

Width = 0.4
